endpoint: https://potloc.atlassian.net
login: mat@potloc.com
authentication-method: api-token

custom-commands:
  - name: project
    help: display current project shorthand
    script: |-
      echo $JIRA_PROJECT

  - name: mine
    help: display issues assigned to me
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
          # if `project: ...` configured just list the issues for current project
          {{jira}} list --template table --query "resolution = unresolved and assignee=currentuser() and project = $JIRA_PROJECT ORDER BY priority asc, created"
      else
          # otherwise list issues for all project
          {{jira}} list --template table --query "resolution = unresolved and assignee=currentuser() ORDER BY priority asc, created"
      fi

  - name: sprint
    help: display issues for active sprint
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
          # if `project: ...` configured just list the issues for current project
          {{jira}} list --template table --query "sprint in openSprints() and type != epic and resolution = unresolved and project=$JIRA_PROJECT ORDER BY rank asc, created"
      else
          # otherwise list issues for all project
          echo "\"project: ...\" configuration missing from .jira.d/config.yml"
      fi

  - name: summary
    help: create a branch from an issue summary
    args:
      - name: ISSUE_NUMBER
        required: true
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
        jira view $JIRA_PROJECT-{{args.ISSUE_NUMBER}} -t debug | jq -r ".fields.summary"
      else
        jira view {{args.ISSUE_NUMBER}} -t debug | jq -r ".fields.summary"
      fi

  - name: standup
    help: Every story changes of yesterday
    script: |-
      {{jira}} list --template table --query "project = POT AND assignee=currentuser() AND status in (done, 'in progress', 'in review') AND statusCategoryChangedDate >= -1d ORDER BY key ASC, summary DESC, cf[10005] DESC, lastViewed DESC"
