#!/usr/bin/env ruby
# frozen_string_literal: true

require "active_support/inflector"

def jira_issue_number
  ARGV[0]
end

def jira_summary
  `jira summary #{jira_issue_number}`.strip
end

def jira_project
  `jira project`.strip
end

def branch_name
  "#{jira_project}-#{jira_issue_number}-#{jira_summary.parameterize}"
end

system("git checkout -b #{branch_name}")
