#!/usr/bin/env ruby
# frozen_string_literal: true

def commit_message
  ARGV[0]
end

def jira_issue_number
  current_branch = `git rev-parse --abbrev-ref HEAD`
  current_branch.match(/^\w*-?\d*/).to_s
end

def potloc_commit_message
  [jira_issue_number, commit_message].compact.join(" ")
end

system("git commit -m \"#{potloc_commit_message}\"")
