#!/usr/bin/env ruby
# frozen_string_literal: true

PROJECT_SHORT_NAMES = %w(POT HLP FIX RAK)

def current_branch
  `git rev-parse --abbrev-ref HEAD`.strip
end

def jira_project
  @jira_project ||= current_branch.split("-").first
end

def jira_issue
  @jira_issue_number ||= begin
    match = current_branch.match(/^(\w*-?\d*)/)
    match && match[1]
  end
end

def jira_summary
  `jira view #{jira_issue} -t debug | jq -r ".fields.summary"`.strip
end

def jira_description
  %(`jira view --field=description -t debug #{jira_issue} | jq -r ".fields.description"`)
end

def accomplishments
  commits = `git log --pretty="%s" origin/develop..HEAD`.split("\n").reverse.map(&:strip)
  commits.map do |commit|
    %(- [x] #{commit.match(/^#{jira_project}-?\d*\W(.*)/)[1]})
  end.join("\n")
end

def github_pr_title
  [jira_issue, jira_summary].compact.join(" ")
end

def github_pr_message
  "### Why\n\n" \
  "#{jira_description}\n\n" \
  "### Ticket\n\n" \
  "https://potloc.atlassian.net/browse/#{jira_issue}\n\n" \
  "### Accomplishments\n\n" \
  "#{accomplishments}\n\n" \
  "### Testing\n\n" \
  "_none_"
end

if jira_project == "FIX"
  system("hub pull-request --base develop \
                           --push \
                           --draft \
                           --assign mathieugagne")
else
  system("hub pull-request --base develop \
                           --push \
                           --draft \
                           --assign mathieugagne \
                           --message \"#{github_pr_title}\" \
                           --message \"#{github_pr_message}\"")
end
