#!/usr/bin/env ruby
# frozen_string_literal: true

def current_branch
  `git rev-parse --abbrev-ref HEAD`.strip
end

def jira_issue_number
  match = current_branch.match(/^#{jira_project}-(\d*)/)
  match && match[1]
end

def jira_summary
  `jira summary #{jira_issue_number}`.strip
end

def jira_description
  %(`jira view --field=description -t debug #{jira_project}-#{jira_issue_number} | jq -r ".fields.description"`)
end

def jira_project
  `jira project`.strip
end

def accomplishments
  commits = `git log --pretty="%s" origin/develop..HEAD`.split("\n").reverse.map(&:strip)
  commits.map do |commit|
    %(- [x] #{commit.match(/^#{jira_project}-\d*\W(.*)/)[1]})
  end.join("\n")
end

def github_pr_title
  "#{jira_project}-#{jira_issue_number} #{jira_summary}"
end

def github_pr_message
  "### Why\n\n" \
  "#{jira_description}\n\n" \
  "### Ticket\n\n" \
  "https://potloc.atlassian.net/browse/#{jira_project}-#{jira_issue_number}\n\n" \
  "### Accomplishments\n\n" \
  "#{accomplishments}\n\n" \
  "### Testing\n\n" \
  "_none_"
end

if jira_issue_number
  system("hub pull-request --base develop \
                           --push \
                           --draft \
                           --assign mathieugagne \
                           --message \"#{github_pr_title}\" \
                           --message \"#{github_pr_message}\"")
else
  system("hub pull-request --base develop \
                           --push \
                           --draft \
                           --assign mathieugagne")
end
