#!/usr/bin/env ruby
# frozen_string_literal: true

require "active_support/core_ext/object"

PROJECT_SHORT_NAMES = %w(POT HLP FIX RAK)

def current_branch
  `git rev-parse --abbrev-ref HEAD`.strip
end

def jira_issue
  @jira_issue ||= begin
    current_branch = `git rev-parse --abbrev-ref HEAD`
    current_branch.match(/^\w*-?\d*/).to_s
  end
end

def jira_summary
  `jira view #{jira_issue} -t debug | jq -r ".fields.summary"`.strip
end

def jira_description
  %(`jira view --field=description -t debug #{jira_issue} | jq -r ".fields.description"`)
end

def accomplishments
  commits.map do |commit|
    %(- [x] #{commit.match(/^\w*-?\d*\W(.*)/)[1]})
  end.join("\n")
end

def commits
  `git log --pretty="%s" origin/develop..HEAD`.split("\n").reverse.map(&:strip)
end

def github_pr_title
  return commits.first if commits.length == 1

  [jira_issue, jira_summary].compact.join(" ")
end

def github_pr_message
  return "" if jira_issue.blank? || jira_summary.blank?

  "### Why\n\n" \
  "> #{jira_description}\n\n" \
  "### Ticket\n\n" \
  "https://potloc.atlassian.net/browse/#{jira_issue}\n\n" \
  "### Accomplishments\n\n" \
  "#{accomplishments}\n\n" \
  "### Testing\n\n" \
  "_none_"
end

system("hub pull-request --base develop \
                         --push \
                         --draft \
                         --assign mathieugagne \
                         --message \"#{github_pr_title}\" \
                         --message \"#{github_pr_message}\"")
